baseURL = "https://y2kappa.github.io/beautiful-code/"
languageCode = "en-us"
title = "Beautiful Code"
theme = "archie"
publishDir = "docs"

[params]
	mode="dark" # color-mode â†’ light,dark or auto
	featherIconsCDN=true
	subtitle = "ğŸ‘¨â€ğŸ’» Snippets that make you want to clap ğŸ‘ in awe ğŸ™Œ. Rust ğŸ¦€ OCaml ğŸª Python ğŸ C++"
