baseURL = "https://y2kappa.github.io/blog/"
languageCode = "en-us"
title = ""
theme = "hugo-PaperMod"
publishDir = "docs"
googlefonts = ["Droid Sans", "Fira Mono"]
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'

[params]
	mode="dark" # color-mode â†’ light,dark or auto
	featherIconsCDN=true
	subtitle = "Me talking to my future me."

[params.homeInfoParams]
	Title = "Hi there ğŸ‘‹ ğŸµ"
	Content = "My name is Marius, this is me thinking about life and software, discovering old lessons and learning new stuff."
